/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz1;

/**
 *
 * @author LENOVO
 */
public class cafe extends javax.swing.JFrame {
    
    String pilihan = "";
    int harga_kopi;
    int item =0;

    /**
     * Creates new form cafe
     */
    public cafe() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        fJumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbKopi = new javax.swing.JComboBox<>();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hNama = new javax.swing.JTextField();
        hKopi = new javax.swing.JTextField();
        hHarga = new javax.swing.JTextField();
        hTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hJumlah = new javax.swing.JTextField();
        bSelesai = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\bg cafe 1.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME TO JAVVA CAFE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 243, 21);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Jenis Kopi :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 127, 120, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Jumlah Pesanan :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(51, 173, 150, 19);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Total :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(56, 459, 90, 19);
        getContentPane().add(fNama);
        fNama.setBounds(214, 78, 170, 28);
        getContentPane().add(fJumlah);
        fJumlah.setBounds(214, 167, 170, 28);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setText("A / N :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(51, 84, 70, 19);

        cbKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Kopi --", "Arabica Coffee", "Robusta Coffee", "Liberian Coffee", "Excelsa Coffee" }));
        cbKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKopiActionPerformed(evt);
            }
        });
        getContentPane().add(cbKopi);
        cbKopi.setBounds(214, 120, 170, 31);

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus);
        bHapus.setBounds(174, 224, 100, 23);

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar);
        bKeluar.setBounds(310, 224, 90, 23);

        jLabel9.setText("______________________________________________________________________________");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(14, 253, 390, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel10.setText("A / N :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(56, 290, 70, 19);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Kopi :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 330, 130, 19);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Harga :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(56, 374, 90, 19);
        getContentPane().add(hNama);
        hNama.setBounds(213, 287, 170, 22);
        getContentPane().add(hKopi);
        hKopi.setBounds(213, 327, 170, 22);
        getContentPane().add(hHarga);
        hHarga.setBounds(213, 371, 170, 22);
        getContentPane().add(hTotal);
        hTotal.setBounds(213, 456, 170, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah Pesanan :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(56, 414, 160, 19);
        getContentPane().add(hJumlah);
        hJumlah.setBounds(213, 411, 170, 22);

        bSelesai.setText("Selesai");
        bSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelesaiActionPerformed(evt);
            }
        });
        getContentPane().add(bSelesai);
        bSelesai.setBounds(33, 224, 90, 23);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz1/bg cafe 3.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 430, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
        // TODO add your handling code here:
        pilihan = (String) cbKopi.getSelectedItem();
        switch (pilihan) {
            case "Arabica Coffee":
                harga_kopi = 25000;
                break;
            case "Robusta Coffee":
                harga_kopi = 50000;
                break;
            case "Liberian Coffee":
                harga_kopi = 60000;
                break;
            case "Excelsa Coffee":
                harga_kopi = 75000;
                break;
        }
        hHarga.setText(""+Integer.toString(harga_kopi));
    }//GEN-LAST:event_cbKopiActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        fNama.setText("");
        cbKopi.setSelectedItem("-- Pilih Kopi --");
        fJumlah.setText("");
        hNama.setText("");
        hKopi.setText("");
        hHarga.setText("");
        hJumlah.setText("");
        hTotal.setText("");
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0); 
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelesaiActionPerformed
        // TODO add your handling code here:
        item = Integer.parseInt(fJumlah.getText());
        int TotalHarga = harga_kopi * item;
        
        hNama.setText(fNama.getText());
        hTotal.setText("Rp."+TotalHarga);
        hJumlah.setText(""+item);
        hKopi.setText(""+pilihan);
    }//GEN-LAST:event_bSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSelesai;
    private javax.swing.JComboBox<String> cbKopi;
    private javax.swing.JTextField fJumlah;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField hHarga;
    private javax.swing.JTextField hJumlah;
    private javax.swing.JTextField hKopi;
    private javax.swing.JTextField hNama;
    private javax.swing.JTextField hTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
